### ISSUE TITLE
Нужны ли нам открытые отчеты аудита?

### ISSUE THREAD

**Issue by Zhdun777** [EthereumCommonwealth/Proposals#73]
Последние недели в сообществе идет бурное обсуждение работы отдела аудита Callisto network. За время существования проекта было проведено порядка 300 аудитов, цифра весомая, но есть ли польза от проделанной работы? На данный момент ответ - нет. Криптоиндустрия не принимает такую модель работы и это очевидно.  

На данный момент я вижу две взаимосвязанные проблемы, которые тянут проект на дно. Решить только одну из этих проблем, чтобы получить результат, будет недостаточно. 

**Первая проблема - аудиты без отзывов.** Такая модель не ведет к популяризации проекта, отчеты о проделанной работе в лучшем случае видят разработчики смартов и сообщество Сallisto network. Можно продолжать штамповать отчеты и платить зарплаты аудиторам, но приведет ли это к росту проекта в глазах криптоинудстрии? Требовать фидбеки от разработчиков для популяризации Callisto network это хорошая идея, но при нынешней модели работы это делать бессмысленно, потому как есть вторая проблема... 

**Вторая проблема - полностью открытые отчеты аудита.** Какой здравомыслящий разработчик согласится сообщить своим пользователям об ошибках? Мы довольно редко видим в отчетах отдела аудита критические ошибки, которые могут привести к финансовым потерям. В основном это те ошибки, которые не являются критичными, так стоит ли разработчику заявлять о них простым пользователям и тем самым создавать сомнения в профессионализме команды и сомнения в сохранности вложений? Ответ очевиден - не стоит. 

Я не думаю, что Tron foundation когда-либо согласится работать с Callisto network в таком ключе. Можно сколько угодно долго пытаться навязать свои правила игры криптоиндустрии, но это все-равно что жужжать рядом с  самолетом. Не услышат и просто пролетят мимо в лучшем случае.

**Мое предложение следующее:** сделать отчеты об аудитах частично закрытыми. Если проверенный смарт-контракт не содержит критических ошибок, то отчет о выявленных проблемах направляется только разработчикам. А в github и разделе сайта, который было бы неплохо создать, указывать только сведения о проверенных смарт-контрактах с отметкой о том, что они не содержат критических ошибок. В этом случае проект Callisto network сможет получить отзывы, сможет получить узнаваемость.

**Comment by shivneja** [comment]
I translated your comment for the benefit of others.

“Recent weeks in the community have been a heated discussion of the work of the audit department of Callisto network. During the existence of the project, about 300 audits were carried out, the figure is significant, but is there any benefit from the work done? At the moment, the answer is no. The crypto industry does not accept such a model of work and this is obvious.

At the moment, I see two interrelated problems that are pulling the project to the bottom. Solving only one of these problems to get the result will not be enough.

The first problem is audits without reviews. Such a model does not lead to the popularization of the project, reports on the work done are at best seen by smart developers and the Callisto network community. You can continue to stamp reports and pay salaries to auditors, but will this lead to the growth of the project in the eyes of the crypto industry? It is a good idea to require feedback from developers to popularize Callisto network, but with the current model of work, it makes no sense, because there is a second problem ...

The second problem is fully open audit reports. Which sane developer agrees to report bugs to his users? We rarely see critical errors in the reports of the audit department that can lead to financial losses. Basically, these are errors that are not critical, so is it worth the developer to report them to ordinary users and thereby create doubts about the professionalism of the team and doubts about the safety of investments? The answer is obvious - not worth it.

I do not think that Tron foundation will ever agree to work with Callisto network in this way. You can try to impose your own rules of the game on the crypto industry for as long as you like, but it’s like buzzing next to an airplane. They will not hear and just fly by at best.

My suggestion is to make the audit reports partially closed. If the verified smart contract does not contain critical errors, then a report on the identified problems is sent only to the developers. And in github and the section of the site, which would be nice to create, indicate only information about verified smart contracts with a note that they do not contain critical errors. In this case, the Callisto network project will be able to receive feedback, will be able to get recognition.”

Your comments are very interesting. 
1. As a suggestion can we advertise or promote those Smart Contracts that have rectified the errors found in the audit? 
Secondly, can we promote continuous on-chain monitoring of dApps on Callisto network? The same as @Dexaran was doing with EOS earlier today? As there is increased adoption from large companies, it will be their need ( I feel) to have a secure network without the risk of an attack.
